CREATE DATABASE Veto;

USE Veto;

CREATE TABLE IF NOT EXISTS Quotes (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(250) DEFAULT NULL,
    author VARCHAR(250) DEFAULT NULL,
    description VARCHAR(500) DEFAULT NULL,
    type VARCHAR(100) DEFAULT NULL,
    status VARCHAR(100) DEFAULT NULL,
    topic VARCHAR(100) DEFAULT NULL,
    hashtags VARCHAR(250) DEFAULT NULL,
    votes VARCHAR(100) DEFAULT NULL,
    dateCreated DATE DEFAULT NULL,
    dateQuote DATE DEFAULT NULL,
    source VARCHAR(250) DEFAULT NULL,
    party VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY(id)
);